#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at appveyor.com
#
#-----------------------------------------------------------------------------

environment:
  matrix:
  - config: Release

shallow_clone: true

# Operating system (build VM template)
os: Visual Studio 2015

platform: x64

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\osmium-tool

install:
  - cd c:\projects
  - git clone --depth 1 https://github.com/osmcode/libosmium
  - git clone --depth 1 https://github.com/mapbox/protozero

build_script:
  - cd c:\projects/osmium-tool
  - build-appveyor.bat

artifacts:
  - path: build
    name: OsmiumTool
